language: ruby
cache: bundler
gemfile: DPP4_Home/Gemfile
script:
  - cd DPP4_Home
  - bundle exec jekyll build 
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
    - develop
rvm:
 - 2.5

cache: bundler
