language: ruby
cache: bundler
gemfile: DPP4_Home/Gemfile
script:
  - cd DPP4_Home
  - bundle exec jekyll build 
  - bundle exec htmlproofer ./_site
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
    - develop
rvm:
 - 2.5

env:
  global: 
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt: 
    packages:
    - libcurl4-openssl-dev

sudo: false
  
cache: bundler

notifications:
  email: false 
